INSERT INTO shelters
(name, street_address, city, province, postal_code, country, phone, email, thumbnail_url, website_url,capacity, couples, female_only, male_only, family, pets)
VALUES
('Brenda`s House', '1921 28 St SW', 'Calgary', 'AB', 'T3E 2H1', 'Canada', '(403) 242-8575', 'brendas@childrenscottage.ab.ca', 'https://i.ibb.co/mS3KykF/brendas.jpg', 'childrenscottage.ab.ca/main/brenda-s-house/', 50, true, false, false, true, true),
('WHC, Inc.', '209 8 Ave SW', 'Calgary', 'AB', 'T2P 1B7', 'Canada', '(587) 245-8575', 'info@whcinc.ca', 'https://i.ibb.co/Ry6Pj9s/whcinc.png', 'whcinc.ca', 25, false, true, false, true, true),
('The Mustard Seed Shelter', '7025 44 St SE', 'Calgary', 'AB', 'T2C 4E8', 'Canada', '(403) 723-9422', 'contact@theseed.ca', 'https://i.ibb.co/G7Dg736/seed.jpg', 'www.theseed.ca', 320, false, true, true, false, true),
('Inn from the Cold', '110 11 Ave SE', 'Calgary', 'AB', 'T2G 0X5', 'Canada', '(403)263-8384', 'contact@innfromthecold.org', 'https://i.ibb.co/kcJZGTg/infromthecold.jpg', 'innfromthecold.org', 140, true, false, false, true, true),
('Calgary Homeless Foundation', '615 Macleod Trail SE', 'Calgary', 'AB', 'T2G 4T8', 'Canada', '(403) 237-6456', 'contact@calgaryhomeless.com', 'https://i.ibb.co/St2RJcP/calgaryhomelessfoundation.jpg', 'calgaryhomeless.com', 60, true, false, false, true, true),
('The Salvation Army Belkin House', '555 Homer St', 'Vancouver', 'BC', 'V6B 1K8', 'Canada', '(604) 681-3405', 'contact@belkinhouse.ca', 'https://i.ibb.co/W0kSHmj/salvation.jpg', 'belkinhouse.ca', 120, true, true, false, true, false),
('Catholic Charities Mens Hostel', '1056 Comox St', 'Vancouver', 'BC', 'V6Z 1Y6', 'Canada', '(604) 443-3292', 'mens-hostel@rcav.org', 'https://i.ibb.co/m8d2Wht/03-05-19news-12th-Cambie-Two-of-the-four-shelters-1138-Burrard-glass-and-828-Cambie-brick-Photo-Dan.jpg', 'rcav.org/mens-hostel', 45, true, false, true, false, true),
('Yukon Shelter and Housing Centre', '2088 Yukon St', 'Vancouver', 'BC', 'V5Y 4B1', 'Canada', '(604) 264-1680', 'contactus@lookoutsociety.ca', 'https://i.ibb.co/PZX7TjB/yukon.jpg', 'lookoutsociety.ca', 90, true, true, false, true, false),
('Triage Shelter', '707 Powell St', 'Vancouver', 'BC', 'V6A 1H5', 'Canada', '(604) 254-3700', 'contactus@raincityhousing.org', 'https://i.ibb.co/ZBt2Sgg/triage.jpg', 'raincityhousing.org', 75, true, true, false, true, false),
('Downtown Eastside Womens', '412 E Cordova St', 'Vancouver', 'BC', 'V6A 1L6', 'Canada', '(604) 423-4807', 'contact@dewc.ca', 'https://i.ibb.co/7X4zdF3/Downtown-Eastside-Women-s-Centre-facade-is-pictured-in-Vancouver-British-Columbia-Canada-January-15.jpg', 'dewc.ca/emergency-shelter', 65, true, true, false, true, false),
('Salvation Army New Hope', '29 Leslie St', 'Toronto', 'ON', 'M4M 3C3', 'Canada', '(647) 362-3062', 'contact@torontohhs.org', 'https://i.ibb.co/TmGLWkz/salv-newhop.webp', 'torontohhs.org/shelters/new-hope', 120, true, true, false, true, false),
('Salvation Army - Evangeline Residence', '2808 Dundas St W', 'Toronto', 'ON', 'M6P 1Y5', 'Canada', '(416) 443-3292', 'evangeline@torontohhs.org', 'https://i.ibb.co/ZNnPTdw/evang.jpg', 'torontohhs.org', 45, true, false, true, false, true),
('Woodgreen Red Door Family', '21 Carlaw Ave', 'Toronto', 'ON', 'M4M 2R6', 'Canada', '(416) 915-5698', 'contact@reddoorshelter.ca', 'https://i.ibb.co/ZRjt9vC/redoor.jpg', 'www.reddoorshelter.ca', 90, true, true, false, true, false),
('Cornerstone Place', '616 Vaughan Rd', 'York', 'ON', 'M6C 2R5', 'Canada', '(647) 346-0616', 'contact@cornerstone.org', 'https://i.ibb.co/vd8ZJQW/coor.jpg', 'cornerstone.org', 75, true, true, false, true, false),
('Homes First Society', '805 Wellington St W', 'Toronto', 'ON', 'M5V 1G8', 'Canada', '(416) 395-0928', 'contact@homesfirst.on.ca', 'https://i.ibb.co/q0LVBV9/homes.jpg', 'homesfirst.on.ca', 65, true, true, false, true, false);